sudo: required
services:
  - docker

before_install:
  - docker build -t hammerandnail/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hammerandnail/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-555212973365"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
